import type { ScannerAdapter, ScanContext as CoreScanContext } from "@kodeaman/core";
import type { NormalizedFinding, RepoContext } from "@kodeaman/schema";
import { access } from "node:fs/promises";
import { join } from "node:path";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import type { ScanContext, SpotbugsBugInstance, SpotbugsRawOutput } from "./types.js";
import { hashParts, mapCategory, mapOwaspCategory, mapSeverity } from "./mapper.js";
const execFileAsync = promisify(execFile); const DETECTION_FILES = ["pom.xml", "build.gradle", "build.gradle.kts"];
const spotbugsCweMap: Record<string, string[]> = { SQL: ["CWE-89"], XSS: ["CWE-79"], PATH_TRAVERSAL: ["CWE-22"], COMMAND_INJECTION: ["CWE-78"], HARD_CODE_PASSWORD: ["CWE-798"], WEAK_MESSAGE_DIGEST: ["CWE-327"], PREDICTABLE_RANDOM: ["CWE-330"], XXE: ["CWE-611"] };
export class SpotbugsAdapter implements ScannerAdapter { readonly name = "spotbugs";
 async scan(context: ScanContext & Partial<CoreScanContext>, repoContext?: RepoContext): Promise<NormalizedFinding[]> { const targetPath = context.targetPath ?? context.repoRoot; if (!targetPath) throw new Error("spotbugs adapter requires targetPath or repoRoot."); await this.ensureDetected(targetPath); await this.ensureBinary(); const raw = await this.runTool(targetPath, context); return this.parseOutput(raw, repoContext); }
 private async ensureDetected(targetPath: string) { for (const file of DETECTION_FILES) { try { await access(join(targetPath, file)); return; } catch {} } throw new Error(`spotbugs could not detect a Java project. Expected one of: ${DETECTION_FILES.join(", ")}`); }
 private async ensureBinary() { const checker = process.platform === "win32" ? "where" : "which"; try { await execFileAsync(checker, ["spotbugs"], { timeout: 10_000 }); } catch { throw new Error("spotbugs requires the `spotbugs` binary. Install SpotBugs and ensure it is available on PATH before scanning."); } }
 private async runTool(targetPath: string, context: ScanContext): Promise<SpotbugsRawOutput> { const jarPath = context.jarPath ?? targetPath; const args = ["-textui", "-xml", "-effort:max", jarPath, ...(context.extraArgs ?? [])]; try { const { stdout } = await execFileAsync("spotbugs", args, { cwd: targetPath, timeout: context.timeout ?? 300_000, maxBuffer: 50 * 1024 * 1024 }); return this.parseXml(stdout); } catch (error: unknown) { if (error && typeof error === "object" && "stdout" in error) { const stdout = (error as { stdout?: string }).stdout; if (stdout) return this.parseXml(stdout); } throw error; } }
 private parseXml(xml: string): SpotbugsRawOutput { const bugs: SpotbugsBugInstance[] = []; const bugRegex = /<BugInstance([^>]*)>([\s\S]*?)<\/BugInstance>/g; for (const match of xml.matchAll(bugRegex)) { const attrs = this.attrs(match[1] ?? ""); const body = match[2] ?? ""; const source = body.match(/<SourceLine([^>]*)\/?>(?:<\/SourceLine>)?/); const sourceAttrs = this.attrs(source?.[1] ?? ""); const message = body.match(/<LongMessage>([\s\S]*?)<\/LongMessage>/)?.[1] ?? body.match(/<ShortMessage>([\s\S]*?)<\/ShortMessage>/)?.[1]; bugs.push({ type: attrs.type ?? "SPOTBUGS", priority: attrs.priority, rank: attrs.rank, category: attrs.category, abbrev: attrs.abbrev, message: message?.replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&amp;/g, "&"), className: this.attrs(body.match(/<Class([^>]*)>/)?.[1] ?? "").classname, sourcePath: sourceAttrs.sourcepath, startLine: sourceAttrs.start ? Number.parseInt(sourceAttrs.start, 10) : undefined, endLine: sourceAttrs.end ? Number.parseInt(sourceAttrs.end, 10) : undefined }); } return { bugs }; }
 private attrs(input: string): Record<string, string> { const attrs: Record<string, string> = {}; for (const match of input.matchAll(/([A-Za-z_:][-A-Za-z0-9_:.]*)="([^"]*)"/g)) attrs[match[1]] = match[2]; return attrs; }
 parseOutput(raw: SpotbugsRawOutput, repoContext?: RepoContext): NormalizedFinding[] { return raw.bugs.map((b) => this.mapBug(b, repoContext)); }
 private mapBug(b: SpotbugsBugInstance, repoContext?: RepoContext): NormalizedFinding { const cwes = b.cwe ? [`CWE-${b.cwe.replace(/^CWE-/i, "")}`] : (spotbugsCweMap[b.type] ?? []); const prioritySeverity = b.priority === "1" ? "high" : b.priority === "2" ? "medium" : b.priority === "3" ? "low" : b.category === "SECURITY" ? "high" : "medium"; const severity = mapSeverity(prioritySeverity); const category = mapCategory(cwes); const id = hashParts(["spotbugs", b.type, b.sourcePath ?? b.className ?? "", String(b.startLine ?? "")]); return { schemaVersion: "1.0.0", findingId: id, dedupeKey: hashParts([b.type, b.sourcePath ?? b.className ?? "", String(b.startLine ?? "")], 16), source: "spotbugs", category, surface: "source-code", owaspCategory: mapOwaspCategory(cwes), severity, confidence: b.rank && Number.parseInt(b.rank, 10) <= 10 ? "high" : "medium", status: "open", title: `${b.type}: ${b.message ?? b.category ?? "SpotBugs finding"}`, description: b.message ?? b.type, location: { filePath: b.sourcePath, startLine: b.startLine, endLine: b.endLine, component: b.className }, evidence: [{ type: "scanner-message", label: "SpotBugs bug pattern", content: [`Type: ${b.type}`, b.message ? `Message: ${b.message}` : "", b.className ? `Class: ${b.className}` : ""].filter(Boolean).join("\n") }], classification: { cwe: cwes, tags: ["java", "sast", b.type, b.category ?? "spotbugs"] }, raw: { tool: "spotbugs", toolRuleId: b.type, toolFindingId: id, rawSeverity: b.priority, rawConfidence: b.rank, rawCategory: b.category }, repoContext, prioritization: { baseSeverity: severity, adjustedSeverity: severity, priorityScore: 0, confidenceScore: 60, reasons: ["Java SAST finding from SpotBugs"] }, coaching: { titleEn: `Java security issue: ${b.type}`, titleId: `Masalah keamanan Java: ${b.type}`, summaryEn: b.message ?? b.type, summaryId: b.message ?? b.type, whyItMattersEn: "Java static-analysis findings can indicate exploitable patterns in server-side code.", whyItMattersId: "Temuan analisis statis Java dapat menunjukkan pola yang dapat dieksploitasi pada kode server-side.", remediationEn: ["Review the flagged class and method", "Replace unsafe APIs or constrain inputs", "Rebuild and rerun SpotBugs after the fix"], remediationId: ["Tinjau class dan method yang ditandai", "Ganti API yang tidak aman atau batasi input", "Build ulang dan jalankan SpotBugs setelah perbaikan"], lessonId: "java-sast" }, gamification: { issueFamily: category }, detectedAt: new Date().toISOString() }; }
}
