import type { ScannerAdapter, ScanContext as CoreScanContext } from "@kodeaman/core";
import type { NormalizedFinding, RepoContext, SeverityLevel } from "@kodeaman/schema";
import { access } from "node:fs/promises";
import { join } from "node:path";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import type { CargoAuditRawOutput, CargoAuditVulnerability, ScanContext } from "./types.js";
import { hashParts } from "./mapper.js";
const execFileAsync = promisify(execFile); const DETECTION_FILES = ["Cargo.toml", "Cargo.lock"];
function mapRustSecSeverity(v: CargoAuditVulnerability): SeverityLevel { const cvss = Number.parseFloat(v.advisory.cvss ?? ""); if (cvss >= 9) return "critical"; if (cvss >= 7) return "high"; if (cvss >= 4) return "medium"; if (cvss > 0) return "low"; return "medium"; }
export class CargoAuditAdapter implements ScannerAdapter { readonly name = "cargo-audit";
 async scan(context: ScanContext & Partial<CoreScanContext>, repoContext?: RepoContext): Promise<NormalizedFinding[]> { const targetPath = context.targetPath ?? context.repoRoot; if (!targetPath) throw new Error("cargo-audit adapter requires targetPath or repoRoot."); await this.ensureDetected(targetPath); await this.ensureBinary(); return this.parseOutput(await this.runTool(targetPath, context), repoContext); }
 private async ensureDetected(targetPath: string) { for (const file of DETECTION_FILES) { try { await access(join(targetPath, file)); return; } catch {} } throw new Error(`cargo-audit could not detect a Rust project. Expected one of: ${DETECTION_FILES.join(", ")}`); }
 private async ensureBinary() { const checker = process.platform === "win32" ? "where" : "which"; try { await execFileAsync(checker, ["cargo"], { timeout: 10_000 }); } catch { throw new Error("cargo-audit requires the `cargo` binary and cargo-audit subcommand. Install cargo-audit and ensure cargo is available on PATH before scanning."); } }
 private async runTool(targetPath: string, context: ScanContext): Promise<CargoAuditRawOutput> { const args = ["audit", "--json", ...(context.extraArgs ?? [])]; try { const { stdout } = await execFileAsync("cargo", args, { cwd: targetPath, timeout: context.timeout ?? 300_000, maxBuffer: 50 * 1024 * 1024 }); return JSON.parse(stdout || "{}") as CargoAuditRawOutput; } catch (error: unknown) { if (error && typeof error === "object" && "stdout" in error) { const stdout = (error as { stdout?: string }).stdout; if (stdout) return JSON.parse(stdout) as CargoAuditRawOutput; } throw error; } }
 parseOutput(raw: CargoAuditRawOutput, repoContext?: RepoContext): NormalizedFinding[] { return (raw.vulnerabilities?.list ?? []).map((v) => this.mapVulnerability(v, repoContext)); }
 private mapVulnerability(v: CargoAuditVulnerability, repoContext?: RepoContext): NormalizedFinding { const severity = mapRustSecSeverity(v); const pkg = v.package?.name ?? v.advisory.package; const version = v.package?.version ?? "unknown"; const id = hashParts(["cargo-audit", v.advisory.id, pkg, version]); const cves = (v.advisory.aliases ?? []).filter((a) => a.startsWith("CVE-")); return { schemaVersion: "1.0.0", findingId: id, dedupeKey: hashParts([v.advisory.id, pkg, version], 16), source: "cargo-audit", category: "sca", surface: "dependency", owaspCategory: "A06-vulnerable-components", severity, confidence: "high", status: "open", title: `${v.advisory.title} in ${pkg}`, description: v.advisory.description ?? v.advisory.title, location: { filePath: "Cargo.lock", component: pkg }, evidence: [{ type: "scanner-message", label: "RustSec advisory", content: [`Advisory: ${v.advisory.id}`, `Package: ${pkg}@${version}`, `Patched: ${(v.versions?.patched ?? []).join(", ") || "unknown"}`, v.advisory.url ? `URL: ${v.advisory.url}` : ""].filter(Boolean).join("\n") }], classification: { cve: cves, owasp: ["A06:2021"], tags: ["rust", "sca", "rustsec", ...(v.advisory.categories ?? [])] }, raw: { tool: "cargo-audit", toolRuleId: v.advisory.id, toolFindingId: id, toolUrl: v.advisory.url, rawSeverity: v.advisory.cvss, rawCategory: "sca" }, repoContext, prioritization: { baseSeverity: severity, adjustedSeverity: severity, priorityScore: 0, confidenceScore: 90, reasons: ["RustSec advisory for dependency"] }, coaching: { titleEn: `Vulnerable Rust crate: ${pkg}`, titleId: `Crate Rust rentan: ${pkg}`, summaryEn: v.advisory.title, summaryId: v.advisory.title, whyItMattersEn: "Known vulnerable crates can expose Rust applications to publicly documented attacks.", whyItMattersId: "Crate yang diketahui rentan dapat mengekspos aplikasi Rust ke serangan yang terdokumentasi publik.", remediationEn: ["Upgrade to a patched crate version", "Review the RustSec advisory for workarounds", "Run cargo audit again after updating Cargo.lock"], remediationId: ["Upgrade ke versi crate yang sudah ditambal", "Tinjau advisory RustSec untuk solusi sementara", "Jalankan cargo audit lagi setelah memperbarui Cargo.lock"], lessonId: "rust-sca" }, gamification: { issueFamily: "sca" }, detectedAt: new Date().toISOString() }; }
}
