import type { ScannerAdapter, ScanContext as CoreScanContext } from "@kodeaman/core";
import type { NormalizedFinding, RepoContext } from "@kodeaman/schema";
import { access } from "node:fs/promises";
import { join } from "node:path";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import type { GosecIssue, GosecRawOutput, ScanContext } from "./types.js";
import { hashParts, mapCategory, mapOwaspCategory, mapSeverity } from "./mapper.js";
const execFileAsync = promisify(execFile); const DETECTION_FILES = ["go.mod", "go.sum"];
function cwes(issue: GosecIssue): string[] { return issue.cwe?.id ? [`CWE-${issue.cwe.id}`] : []; }
export class GosecAdapter implements ScannerAdapter { readonly name = "gosec";
 async scan(context: ScanContext & Partial<CoreScanContext>, repoContext?: RepoContext): Promise<NormalizedFinding[]> { const targetPath = context.targetPath ?? context.repoRoot; if (!targetPath) throw new Error("gosec adapter requires targetPath or repoRoot."); await this.ensureDetected(targetPath); await this.ensureBinary(); return this.parseOutput(await this.runTool(targetPath, context), repoContext); }
 private async ensureDetected(targetPath: string) { for (const file of DETECTION_FILES) { try { await access(join(targetPath, file)); return; } catch {} } throw new Error(`gosec could not detect a Go project. Expected one of: ${DETECTION_FILES.join(", ")}`); }
 private async ensureBinary() { const checker = process.platform === "win32" ? "where" : "which"; try { await execFileAsync(checker, ["gosec"], { timeout: 10_000 }); } catch { throw new Error("gosec requires the `gosec` binary. Install gosec and ensure it is available on PATH before scanning."); } }
 private async runTool(targetPath: string, context: ScanContext): Promise<GosecRawOutput> { const args = ["-fmt=json", "./...", ...(context.extraArgs ?? [])]; try { const { stdout } = await execFileAsync("gosec", args, { cwd: targetPath, timeout: context.timeout ?? 300_000, maxBuffer: 50 * 1024 * 1024 }); return JSON.parse(stdout || '{"Issues":[]}') as GosecRawOutput; } catch (error: unknown) { if (error && typeof error === "object" && "stdout" in error) { const stdout = (error as { stdout?: string }).stdout; if (stdout) return JSON.parse(stdout) as GosecRawOutput; } throw error; } }
 parseOutput(raw: GosecRawOutput, repoContext?: RepoContext): NormalizedFinding[] { return (raw.Issues ?? []).map((i) => this.mapIssue(i, repoContext)); }
 private mapIssue(i: GosecIssue, repoContext?: RepoContext): NormalizedFinding { const findingCwes = cwes(i); const severity = mapSeverity(i.severity); const category = mapCategory(findingCwes); const line = Number.parseInt(i.line, 10) || undefined; const id = hashParts(["gosec", i.rule_id, i.file, i.line]); return { schemaVersion: "1.0.0", findingId: id, dedupeKey: hashParts([i.rule_id, i.file, i.line], 16), source: "gosec", category, surface: "source-code", owaspCategory: mapOwaspCategory(findingCwes), severity, confidence: i.confidence?.toLowerCase() === "high" ? "high" : i.confidence?.toLowerCase() === "low" ? "low" : "medium", status: "open", title: `${i.rule_id}: ${i.details}`, description: i.details, location: { filePath: i.file, startLine: line, startColumn: Number.parseInt(i.column ?? "", 10) || undefined, snippet: i.code }, evidence: [{ type: "code", label: "gosec finding", content: i.code ?? i.details }], classification: { cwe: findingCwes, tags: ["go", "sast", i.rule_id] }, raw: { tool: "gosec", toolRuleId: i.rule_id, toolFindingId: id, toolUrl: i.cwe?.url, rawSeverity: i.severity, rawConfidence: i.confidence, rawCategory: category }, repoContext, prioritization: { baseSeverity: severity, adjustedSeverity: severity, priorityScore: 0, confidenceScore: 60, reasons: ["Go SAST finding from gosec"] }, coaching: { titleEn: `Go security issue: ${i.rule_id}`, titleId: `Masalah keamanan Go: ${i.rule_id}`, summaryEn: i.details, summaryId: i.details, whyItMattersEn: "Unsafe Go code can turn trusted services into paths for injection, credential exposure, or insecure network behavior.", whyItMattersId: "Kode Go yang tidak aman dapat membuat layanan tepercaya menjadi jalur injeksi, paparan kredensial, atau perilaku jaringan yang tidak aman.", remediationEn: ["Review the flagged code and data flow", "Use safe standard-library APIs and validate external input", "Add tests for secure behavior"], remediationId: ["Tinjau kode dan alur data yang ditandai", "Gunakan API standar yang aman dan validasi input eksternal", "Tambahkan pengujian untuk perilaku aman"], lessonId: "go-sast" }, gamification: { issueFamily: category }, detectedAt: new Date().toISOString() }; }
}
