import type { ScannerAdapter, ScanContext as CoreScanContext } from "@kodeaman/core";
import type { NormalizedFinding, RepoContext } from "@kodeaman/schema";
import { access } from "node:fs/promises";
import { join } from "node:path";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import type { BanditRawOutput, BanditResult, ScanContext } from "./types.js";
import { hashParts, mapCategory, mapCwes, mapOwaspCategory, mapSeverity } from "./mapper.js";
const execFileAsync = promisify(execFile);
const DETECTION_FILES = ["requirements.txt", "pyproject.toml", "setup.py", "Pipfile"];
export class BanditAdapter implements ScannerAdapter { readonly name = "bandit";
  async scan(context: ScanContext & Partial<CoreScanContext>, repoContext?: RepoContext): Promise<NormalizedFinding[]> { const targetPath = context.targetPath ?? context.repoRoot; if (!targetPath) throw new Error("bandit adapter requires targetPath or repoRoot."); await this.ensureDetected(targetPath); await this.ensureBinary(); return this.parseOutput(await this.runTool(targetPath, context), repoContext); }
  private async ensureDetected(targetPath: string) { for (const file of DETECTION_FILES) { try { await access(join(targetPath, file)); return; } catch {} } throw new Error(`bandit could not detect a Python project. Expected one of: ${DETECTION_FILES.join(", ")}`); }
  private async ensureBinary() { const checker = process.platform === "win32" ? "where" : "which"; try { await execFileAsync(checker, ["bandit"], { timeout: 10_000 }); } catch { throw new Error("bandit requires the `bandit` binary. Install Bandit and ensure it is available on PATH before scanning."); } }
  private async runTool(targetPath: string, context: ScanContext): Promise<BanditRawOutput> { const args = ["-r", targetPath, "-f", "json", ...(context.extraArgs ?? [])]; try { const { stdout } = await execFileAsync("bandit", args, { cwd: targetPath, timeout: context.timeout ?? 300_000, maxBuffer: 50 * 1024 * 1024 }); return JSON.parse(stdout || '{"results":[]}') as BanditRawOutput; } catch (error: unknown) { if (error && typeof error === "object" && "stdout" in error) { const stdout = (error as { stdout?: string }).stdout; if (stdout) return JSON.parse(stdout) as BanditRawOutput; } throw error; } }
  parseOutput(raw: BanditRawOutput, repoContext?: RepoContext): NormalizedFinding[] { return (raw.results ?? []).map((r) => this.mapResult(r, repoContext)); }
  private mapResult(r: BanditResult, repoContext?: RepoContext): NormalizedFinding { const cwes = mapCwes(r.test_id, r.issue_cwe?.id); const severity = mapSeverity(r.issue_severity); const category = mapCategory(cwes); const id = hashParts(["bandit", r.test_id, r.filename, String(r.line_number)]); return { schemaVersion: "1.0.0", findingId: id, dedupeKey: hashParts([r.test_id, r.filename, String(r.line_number)], 16), source: "bandit", category, surface: "source-code", owaspCategory: mapOwaspCategory(cwes), severity, confidence: r.issue_confidence?.toLowerCase() === "high" ? "high" : r.issue_confidence?.toLowerCase() === "low" ? "low" : "medium", status: "open", title: `${r.test_name} (${r.test_id})`, description: r.issue_text, location: { filePath: r.filename, startLine: r.line_number, endLine: r.line_range?.at(-1) ?? r.line_number, snippet: r.code }, evidence: [{ type: "code", label: "Bandit finding", content: r.code ?? r.issue_text }], classification: { cwe: cwes, tags: ["python", "sast", r.test_id] }, raw: { tool: "bandit", toolRuleId: r.test_id, toolFindingId: id, toolUrl: r.more_info, rawSeverity: r.issue_severity, rawConfidence: r.issue_confidence, rawCategory: category }, repoContext, prioritization: { baseSeverity: severity, adjustedSeverity: severity, priorityScore: 0, confidenceScore: 60, reasons: ["Python SAST finding from Bandit"] }, coaching: { titleEn: `Python security issue: ${r.test_name}`, titleId: `Masalah keamanan Python: ${r.test_name}`, summaryEn: r.issue_text, summaryId: r.issue_text, whyItMattersEn: "Unsafe Python patterns can expose applications to injection, secret leakage, or insecure runtime behavior.", whyItMattersId: "Pola Python yang tidak aman dapat mengekspos aplikasi ke injeksi, kebocoran rahasia, atau perilaku runtime yang tidak aman.", remediationEn: ["Review the flagged code path", "Replace the unsafe API or add strict validation", "Add tests that cover the secure behavior"], remediationId: ["Tinjau jalur kode yang ditandai", "Ganti API yang tidak aman atau tambahkan validasi ketat", "Tambahkan pengujian untuk perilaku aman"], lessonId: "python-sast" }, gamification: { issueFamily: category }, detectedAt: new Date().toISOString() }; }
}
